# Generated by Django 4.2.4 on 2023-08-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuiShop', '0007_alter_gallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avatar',
            field=models.ImageField(null=True, upload_to='gallery'),
        ),
    ]
